// Урок 2. There is / There are. Сюжет: воскресная прогулка в парке с друзьями и Винни.
// track = имя файла в public/audio/ без .mp3. Тексты дорожек: tasks/audio-spec.md и AGENTS.md.
// image = id из js/lessons/images.js (пока png нет, показывается emoji).

export default {
  id: "there-is",
  number: 2,
  title: "Что есть в парке?",
  grammar: "There is / There are",
  emoji: "🌳",
  cover: "cover-lesson-2",
  minutes: 15,
  badge: { name: "Park Explorer", emoji: "🧭" },

  intro: {
    bubble: {
      en: "Hello, my friend! Today we are going to the park. Let's see what there is in the park!",
      ru: "Привет, {name}! Сегодня мы идём в парк. Посмотрим, что там есть!",
    },
    track: "l2-intro",
    heading: "Что есть в парке?",
    lead: "Научись говорить «там есть» по-английски: <b>there is</b> для одного предмета и <b>there are</b> для многих. Погуляем по парку вместе с Винни и его друзьями.",
  },

  rule: {
    bubble: {
      en: "Look at the word after 'there is'. One thing or many things?",
      ru: "Смотри на слово после there is. Один предмет или много?",
    },
    track: "l2-rule",
    kicker: "🔎 Винни объясняет",
    heading: "«Там есть»: there is и there are",
    note: "По-русски можно сказать просто «В парке дерево». По-английски так нельзя. Нужно обязательно сказать «там есть»: <b>There is</b> a tree in the park. Секрет простой. Посмотри на слово сразу после there is или there are. Один предмет, значит <b>is</b>. Много, значит <b>are</b>.",
    cards: [
      {
        title: "🌳 There is",
        tone: "simple",
        html: "Один предмет или одно животное. There is a tree. Там есть дерево. There is a dog. Там есть собака. После there is стоит слово <b>a</b> или <b>an</b>: a tree, a dog, an ice cream. Это подсказка, что предмет один.",
        formula: "There <b>is</b> a tree<small>там есть одно дерево</small>",
        signal: "<span>a bench — скамейка</span> · <span>a dog — собака</span> · <span>an ice cream — мороженое</span>",
        examples: [{ en: "There is a big tree in the park.", ru: "В парке есть большое дерево.", track: "l2-ex-1" }],
      },
      {
        title: "🌸 There are",
        tone: "now",
        html: "Два предмета и больше. There are many flowers. Там много цветов. There are two bikes. Там два велосипеда. Подсказки: слова <b>two, three, many, some</b> и окончание <b>-s</b>: ducks, flowers, bikes.",
        formula: "There <b>are</b> many flowers<small>там много цветов</small>",
        signal: "<span>two bikes — два велосипеда</span> · <span>many flowers — много цветов</span> · <span>some children — несколько детей</span>",
        examples: [{ en: "There are many flowers near the pond.", ru: "У пруда много цветов.", track: "l2-ex-2" }],
      },
      {
        title: "❓ Вопрос и «нет»",
        tone: "neutral",
        html: "В вопросе слова меняются местами: <b>Is there</b> a cat in the tree? <b>Are there</b> any ducks on the pond? Короткий ответ: Yes, there is. No, there aren't. Если чего-то нет: There <b>isn't</b> a cat. There <b>aren't</b> any ducks.",
        formula: "Is there…? · Are there…?<small>Yes, there is. · No, there aren't.</small>",
      },
    ],
    button: "В парк!",
  },

  stages: [
    {
      id: "one-many",
      kind: "sort",
      kicker: "🧺 Разминка",
      title: "Один или много?",
      trail: "Разминка",
      bubble: {
        en: "Sort the cards. One thing goes to 'there is', many things go to 'there are'.",
        ru: "Рассортируй карточки. Один предмет отправляй в домик there is, много предметов в домик there are.",
      },
      track: "l2-s1",
      points: 10,
      zones: [
        { id: "is", title: "🌳 There is", sub: "один" },
        { id: "are", title: "🌸 There are", sub: "много" },
      ],
      cards: [
        { label: "a bench", sub: "скамейка", zone: "is" },
        { label: "three ducks", sub: "три утки", zone: "are" },
        { label: "a dog", sub: "собака", zone: "is" },
        { label: "many flowers", sub: "много цветов", zone: "are" },
        { label: "two bikes", sub: "два велосипеда", zone: "are" },
        { label: "an ice cream", sub: "мороженое", zone: "is" },
        { label: "some children", sub: "несколько детей", zone: "are" },
        { label: "a big tree", sub: "большое дерево", zone: "is" },
      ],
      wrongTip: "Посмотри на карточку ещё раз. Слова a и an говорят «один». Слова two, three, many, some и окончание -s говорят «много».",
    },
    {
      id: "in-the-park",
      kind: "choice",
      kicker: "🎯 Что в парке?",
      title: "Is или are?",
      trail: "Практика",
      bubble: {
        en: "Look at the picture and choose: is or are?",
        ru: "Посмотри на картинку и выбери: is или are?",
      },
      track: "l2-s2",
      wrongBubble: "Почти! Посмотри на слово после there. Один предмет или много?",
      points: 10,
      items: [
        {
          text: "There ___ a pond in the park.",
          ru: "В парке есть пруд.",
          options: ["is", "are"],
          answer: "is",
          tip: "A pond, один пруд. Один, значит is.",
          image: "park-pond-ducks",
          track: "l2-c-1",
        },
        {
          text: "There ___ three ducks on the pond.",
          ru: "На пруду три утки.",
          options: ["is", "are"],
          answer: "are",
          tip: "Three ducks, три утки. Много, значит are.",
          image: "park-pond-ducks",
          track: "l2-c-2",
        },
        {
          text: "There ___ a big tree near the playground.",
          ru: "Рядом с площадкой есть большое дерево.",
          options: ["is", "are"],
          answer: "is",
          tip: "A big tree, одно дерево. Один, значит is.",
          image: "park-tree",
          track: "l2-c-3",
        },
        {
          text: "There ___ many flowers under the tree.",
          ru: "Под деревом много цветов.",
          options: ["is", "are"],
          answer: "are",
          tip: "Many flowers, много цветов. Много, значит are.",
          image: "park-flowers",
          track: "l2-c-4",
        },
        {
          text: "There ___ two swings on the playground.",
          ru: "На площадке две качели.",
          options: ["is", "are"],
          answer: "are",
          tip: "Two swings, две качели. Много, значит are.",
          image: "park-swings",
          track: "l2-c-5",
        },
        {
          text: "There ___ a slide next to the swings.",
          ru: "Рядом с качелями есть горка.",
          options: ["is", "are"],
          answer: "is",
          tip: "A slide, одна горка. Один, значит is.",
          image: "park-slide",
          track: "l2-c-6",
        },
        {
          text: "There ___ some children on the football field.",
          ru: "На футбольном поле несколько детей.",
          options: ["is", "are"],
          answer: "are",
          tip: "Some children, несколько детей. Много, значит are.",
          image: "park-football",
          track: "l2-c-7",
        },
        {
          text: "There ___ a squirrel in the tree.",
          ru: "На дереве сидит белка.",
          options: ["is", "are"],
          answer: "is",
          tip: "A squirrel, одна белка. Один, значит is.",
          image: "park-squirrel",
          track: "l2-c-8",
        },
      ],
    },
    {
      id: "type-there",
      kind: "type",
      kicker: "✏️ Впиши сам",
      title: "Напиши there is или there are",
      trail: "Практика",
      bubble: {
        en: "Now type it yourself: there is or there are. Check your spelling!",
        ru: "Теперь напиши сам: there is или there are. Следи за буквами!",
      },
      track: "l2-s3",
      wrongBubble: "Почти! Один предмет или много? Проверь буквы.",
      points: 15,
      placeholder: "there is / there are",
      items: [
        {
          text: "___ a bench under the tree.",
          ru: "Под деревом есть скамейка.",
          answer: "There is",
          alt: ["There's"],
          hint: "a bench: один",
          tip: "A bench, одна скамейка. Пиши: There is.",
          image: "park-bench",
        },
        {
          text: "___ two bikes near the bench.",
          ru: "Рядом со скамейкой два велосипеда.",
          answer: "There are",
          hint: "two bikes: много",
          tip: "Two bikes, два велосипеда. Пиши: There are.",
          image: "park-bikes",
        },
        {
          text: "___ a kite in the sky.",
          ru: "В небе воздушный змей.",
          answer: "There is",
          alt: ["There's"],
          hint: "a kite: один",
          tip: "A kite, один змей. Пиши: There is.",
          image: "park-kite",
        },
        {
          text: "___ five children on the playground.",
          ru: "На площадке пятеро детей.",
          answer: "There are",
          hint: "five children: много",
          tip: "Five children, пятеро детей. Пиши: There are.",
          image: "park-playground",
        },
        {
          text: "___ an ice cream for Vincent!",
          ru: "Есть мороженое для Винни!",
          answer: "There is",
          alt: ["There's"],
          hint: "an ice cream: одно",
          tip: "An ice cream, одно мороженое. Пиши: There is.",
          image: "park-ice-cream",
        },
        {
          text: "___ a fountain in the middle of the park.",
          ru: "В центре парка есть фонтан.",
          answer: "There is",
          alt: ["There's"],
          hint: "a fountain: один",
          tip: "A fountain, один фонтан. Пиши: There is.",
          image: "park-fountain",
        },
        {
          text: "___ many ducks on the pond today.",
          ru: "Сегодня на пруду много уток.",
          answer: "There are",
          hint: "many ducks: много",
          tip: "Many ducks, много уток. Пиши: There are.",
          image: "park-pond-ducks",
        },
        {
          text: "___ a cat in the tree. Vincent is barking!",
          ru: "На дереве кот. Винни лает!",
          answer: "There is",
          alt: ["There's"],
          hint: "a cat: один",
          tip: "A cat, один кот. Пиши: There is.",
          image: "park-cat-tree",
        },
      ],
    },
    {
      id: "build",
      kind: "build",
      kicker: "🧩 Конструктор",
      title: "Собери предложение",
      trail: "Практика",
      bubble: {
        en: "Put the words in the right order. Tap a word to add it, tap again to take it back.",
        ru: "Расставь слова по порядку. Нажми на слово, чтобы добавить его, и ещё раз, чтобы вернуть.",
      },
      track: "l2-s4",
      wrongBubble: "Почти! Начни с there, потом is или are, потом что и где.",
      points: 15,
      items: [
        { answer: "There is a big tree in the park.", ru: "В парке есть большое дерево.", extra: ["are"], image: "park-tree", track: "l2-b-1" },
        { answer: "There are many flowers near the pond.", ru: "У пруда много цветов.", extra: ["is"], image: "park-flowers", track: "l2-b-2" },
        { answer: "There is a dog on the bench.", ru: "На скамейке сидит собака.", extra: ["are"], image: "park-dog", track: "l2-b-3" },
        { answer: "There are two ducks on the pond.", ru: "На пруду две утки.", extra: ["is"], image: "park-pond-ducks", track: "l2-b-4" },
        { answer: "Is there a cat in the tree?", ru: "На дереве есть кот?", extra: ["are"], image: "park-cat-tree", track: "l2-b-5" },
        { answer: "There aren't any bikes in the park.", ru: "В парке нет велосипедов.", extra: ["isn't"], image: "park-bikes", track: "l2-b-6" },
      ],
    },
    {
      id: "final",
      kind: "choice",
      kicker: "🏁 Финальное испытание",
      title: "Вопросы и ответы",
      trail: "Финал",
      bubble: {
        en: "Final round! Questions and answers. Fifteen points for every correct answer. Let's go!",
        ru: "Финал! Вопросы и ответы. Пятнадцать баллов за каждый правильный ответ. Вперёд!",
      },
      track: "l2-s5",
      wrongBubble: "Почти! Вспомни: один предмет is, много are. В вопросе is и are идут первыми.",
      points: 15,
      items: [
        {
          text: "___ there a pond in the park? — Yes, there is.",
          ru: "В парке есть пруд? Да, есть.",
          options: ["Is", "Are"],
          answer: "Is",
          tip: "A pond, один пруд. В вопросе is идёт первым: Is there a pond?",
          track: "l2-f-1",
        },
        {
          text: "___ there any ducks on the pond? — Yes, there are.",
          ru: "На пруду есть утки? Да, есть.",
          options: ["Is", "Are"],
          answer: "Are",
          tip: "Ducks, много уток. В вопросе are идёт первым: Are there any ducks?",
          track: "l2-f-2",
        },
        {
          text: "Is there a cat in the tree? — Yes, there ___.",
          ru: "На дереве есть кот? Да, есть.",
          options: ["is", "are", "isn't"],
          answer: "is",
          tip: "Ответ «да»: Yes, there is. Кот один, значит is.",
          track: "l2-f-3",
        },
        {
          text: "Are there any bikes near the bench? — No, there ___.",
          ru: "Рядом со скамейкой есть велосипеды? Нет.",
          options: ["aren't", "isn't", "are"],
          answer: "aren't",
          tip: "Ответ «нет» про много предметов: No, there aren't.",
          track: "l2-f-4",
        },
        {
          text: "There ___ a slide on the playground, but there isn't a swing.",
          ru: "На площадке есть горка, а качелей нет.",
          options: ["is", "are"],
          answer: "is",
          tip: "A slide, одна горка. Один, значит is.",
          track: "l2-f-5",
        },
        {
          text: "There ___ any children on the football field today.",
          ru: "Сегодня на футбольном поле нет детей.",
          options: ["aren't", "isn't"],
          answer: "aren't",
          tip: "Children, много детей. «Нет» про много предметов: There aren't any children.",
          track: "l2-f-6",
        },
        {
          text: "___ there a squirrel in the tree? — No, there isn't.",
          ru: "На дереве есть белка? Нет.",
          options: ["Is", "Are"],
          answer: "Is",
          tip: "A squirrel, одна белка. В вопросе is идёт первым: Is there a squirrel?",
          track: "l2-f-7",
        },
        {
          text: "Look! There ___ Vincent and his friends near the fountain!",
          ru: "Смотри! У фонтана Винни и его друзья!",
          options: ["are", "is"],
          answer: "are",
          tip: "Vincent and his friends, это уже несколько друзей. Много, значит are.",
          image: "park-friends",
          track: "l2-f-8",
        },
      ],
    },
  ],

  complete: {
    bubble: {
      en: "Fantastic! Now you can say what there is in the park. High paw!",
      ru: "Здорово, {name}! Теперь ты умеешь говорить, что есть в парке. Дай лапу!",
    },
    track: "l2-done",
    heading: "Парк исследован!",
    lead: "Запомни главное. Один предмет: <b>there is</b>. Много предметов: <b>there are</b>. В вопросе is и are идут первыми: Is there…? Are there…?",
    chips: ["🌳 there is", "🌸 there are", "❓ Is there…?"],
  },
};
