// Урок 3. Артикли a / an / the. Сюжет: тот же парк, Варя, подруги и Винни.

export default {
  id: "articles",
  number: 3,
  title: "A, an или the?",
  grammar: "Артикли a / an / the",
  emoji: "🔤",
  cover: "cover-lesson-3",
  minutes: 15,
  badge: { name: "Article Master", emoji: "🎓" },

  intro: {
    bubble: {
      en: "Hello, my friend! Today we meet three tiny words: a, an and the. They are small, but very important!",
      ru: "Привет, {name}! Сегодня мы познакомимся с тремя маленькими словами: a, an и the. Они крошечные, но очень важные!",
    },
    track: "l3-intro",
    heading: "Три маленьких слова: a, an, the",
    lead: "Англичане ставят перед предметом маленькое слово. <b>A</b> или <b>an</b> значит «какой-то, один из многих». <b>The</b> значит «тот самый». Научись выбирать нужное.",
  },

  rule: {
    bubble: {
      en: "Ask yourself: is it the first time, or do we already know it? First time: a or an. We know it: the.",
      ru: "Спроси себя: предмет первый раз или мы его уже знаем? Первый раз: a или an. Уже знаем: the.",
    },
    track: "l3-rule",
    kicker: "🔎 Винни объясняет",
    heading: "«Какой-то» или «тот самый»?",
    note: "Два вопроса помогут выбрать. Первый: мы называем предмет в первый раз или уже знаем, о чём речь? Первый раз, значит <b>a</b> или <b>an</b>. Тот самый, значит <b>the</b>. Второй вопрос только для a и an: с какого звука начинается слово? С гласного, значит <b>an</b>. Когда предметов много (dogs, flowers), a и an не ставим совсем.",
    cards: [
      {
        title: "🐕 a",
        tone: "simple",
        html: "«Какой-то, один из многих». Ставим, когда называем предмет в первый раз. A dog, какая-то собака, любая. A ball, какой-то мяч. Только для одного предмета.",
        formula: "a dog · a ball · a tree<small>один, в первый раз</small>",
        examples: [{ en: "I see a dog in the park.", ru: "Я вижу в парке собаку. Какую-то собаку.", track: "l3-ex-1" }],
      },
      {
        title: "🍎 an",
        tone: "neutral",
        html: "Тот же a, только перед гласным звуком: an apple, an orange, an umbrella, an egg, an ice cream. Так удобнее говорить. Попробуй сказать «a apple», язык спотыкается.",
        formula: "an apple · an egg · an owl<small>перед a, e, i, o, u</small>",
        signal: "<span>an apple — яблоко</span><span>an orange — апельсин</span><span>an umbrella — зонт</span><span>an owl — сова</span>",
      },
      {
        title: "🐩 the",
        tone: "now",
        html: "«Тот самый». Мы оба уже знаем, о чём речь. Второй раз в рассказе: I see a dog. <b>The</b> dog is Vincent! Или единственный на свете: the sun, the moon. The подходит и к одному предмету, и ко многим: the ducks.",
        formula: "the dog · the sun · the ducks<small>тот самый, уже знакомый</small>",
        examples: [{ en: "The dog is Vincent!", ru: "Эта собака, та самая, это Винни!", track: "l3-ex-2" }],
      },
    ],
    button: "Попробовать!",
  },

  stages: [
    {
      id: "a-an",
      kind: "type",
      kicker: "✏️ Разминка",
      title: "A или an?",
      trail: "Разминка",
      bubble: {
        en: "Type a or an. Listen to the first sound of the word!",
        ru: "Напиши a или an. Слушай первый звук слова!",
      },
      track: "l3-s1",
      wrongBubble: "Почти! С какого звука начинается слово? Гласный, значит an.",
      points: 10,
      placeholder: "a / an",
      items: [
        { text: "___ apple", ru: "яблоко", answer: "an", hint: "первый звук [э]", tip: "Apple начинается с гласного звука, значит an apple.", image: "park-apple" },
        { text: "___ bench", ru: "скамейка", answer: "a", hint: "первый звук [б]", tip: "Bench начинается с согласного, значит a bench.", image: "park-bench" },
        { text: "___ ice cream", ru: "мороженое", answer: "an", hint: "первый звук [ай]", tip: "Ice cream начинается с гласного звука, значит an ice cream.", image: "park-ice-cream" },
        { text: "___ umbrella", ru: "зонт", answer: "an", hint: "первый звук [а]", tip: "Umbrella начинается с гласного звука, значит an umbrella.", image: "park-umbrella" },
        { text: "___ dog", ru: "собака", answer: "a", hint: "первый звук [д]", tip: "Dog начинается с согласного, значит a dog.", image: "park-dog" },
        { text: "___ orange", ru: "апельсин", answer: "an", hint: "первый звук [о]", tip: "Orange начинается с гласного звука, значит an orange.", image: "park-orange" },
        { text: "___ tree", ru: "дерево", answer: "a", hint: "первый звук [т]", tip: "Tree начинается с согласного, значит a tree.", image: "park-tree" },
        { text: "___ owl", ru: "сова", answer: "an", hint: "первый звук [ау]", tip: "Owl начинается с гласного звука, значит an owl.", image: "park-owl" },
        { text: "___ egg", ru: "яйцо", answer: "an", hint: "первый звук [э]", tip: "Egg начинается с гласного звука, значит an egg.", image: "park-egg" },
        { text: "___ kite", ru: "воздушный змей", answer: "a", hint: "первый звук [к]", tip: "Kite начинается с согласного, значит a kite.", image: "park-kite" },
      ],
    },
    {
      id: "first-or-known",
      kind: "choice",
      kicker: "🎯 Первый раз или тот самый?",
      title: "A или the?",
      trail: "Практика",
      bubble: {
        en: "First time we talk about it? Say a. We already know it? Say the.",
        ru: "Говорим о предмете в первый раз? Ставь a. Уже знаем его? Ставь the.",
      },
      track: "l3-s2",
      wrongBubble: "Почти! Этот предмет мы видим впервые или уже знаем его?",
      points: 10,
      items: [
        {
          text: "Varya has ___ ball. The ball is red.",
          ru: "У Вари есть мяч. Мяч красный.",
          options: ["a", "the"],
          answer: "a",
          tip: "Мяч называем в первый раз, значит a ball.",
          image: "park-ball",
          track: "l3-c-1",
        },
        {
          text: "Varya has a ball. ___ ball is red.",
          ru: "У Вари есть мяч. Этот мяч красный.",
          options: ["A", "The"],
          answer: "The",
          tip: "Про этот мяч уже сказали, теперь он «тот самый», значит the ball.",
          image: "park-ball",
          track: "l3-c-2",
        },
        {
          text: "There is ___ dog on the bench.",
          ru: "На скамейке сидит собака.",
          options: ["a", "the"],
          answer: "a",
          tip: "Какая-то собака, видим её в первый раз, значит a dog.",
          image: "park-dog",
          track: "l3-c-3",
        },
        {
          text: "Look at ___ dog! It's Vincent!",
          ru: "Посмотри на эту собаку! Это же Винни!",
          options: ["a", "the"],
          answer: "the",
          tip: "Мы показываем на конкретную собаку, ту самую, значит the dog.",
          image: "park-varya-vincent",
          track: "l3-c-4",
        },
        {
          text: "I can see ___ squirrel in the tree.",
          ru: "Я вижу на дереве белку.",
          options: ["a", "the"],
          answer: "a",
          tip: "Белку заметили только что, в первый раз, значит a squirrel.",
          image: "park-squirrel",
          track: "l3-c-5",
        },
        {
          text: "___ squirrel is eating a nut.",
          ru: "Эта белка ест орех.",
          options: ["A", "The"],
          answer: "The",
          tip: "Про белку уже говорили, значит the squirrel.",
          image: "park-squirrel",
          track: "l3-c-6",
        },
        {
          text: "___ sun is shining today.",
          ru: "Сегодня светит солнце.",
          options: ["A", "The"],
          answer: "The",
          tip: "Солнце одно на всём свете, значит the sun.",
          image: "sky-sun",
          track: "l3-c-7",
        },
        {
          text: "We are having ___ picnic in the park.",
          ru: "У нас пикник в парке.",
          options: ["a", "the"],
          answer: "a",
          tip: "Про пикник говорим в первый раз, значит a picnic.",
          image: "park-picnic",
          track: "l3-c-8",
        },
      ],
    },
    {
      id: "type-article",
      kind: "type",
      kicker: "✏️ Впиши артикль",
      title: "Напиши a, an или the",
      trail: "Практика",
      bubble: {
        en: "Type the right word: a, an or the. Two questions: first time or not? Vowel sound or not?",
        ru: "Напиши нужное слово: a, an или the. Два вопроса: первый раз или нет? Гласный звук или нет?",
      },
      track: "l3-s3",
      wrongBubble: "Почти! Сначала спроси: первый раз или тот самый? Потом: гласный звук?",
      points: 15,
      placeholder: "a / an / the",
      items: [
        { text: "There is ___ big tree in the park.", ru: "В парке есть большое дерево.", answer: "a", hint: "первый раз, звук [б]", tip: "Дерево называем в первый раз, big начинается с согласного, значит a big tree.", image: "park-tree" },
        { text: "___ tree is very old.", ru: "Это дерево очень старое.", answer: "the", hint: "тот самый", tip: "Про дерево уже сказали, значит the tree.", image: "park-tree" },
        { text: "There is ___ owl in the tree.", ru: "На дереве сидит сова.", answer: "an", hint: "первый раз, звук [ау]", tip: "Сова в первый раз, owl начинается с гласного звука, значит an owl.", image: "park-owl" },
        { text: "___ owl is sleeping.", ru: "Сова спит.", answer: "the", hint: "тот самый", tip: "Про сову уже сказали, значит the owl.", image: "park-owl" },
        { text: "Varya is eating ___ ice cream.", ru: "Варя ест мороженое.", answer: "an", hint: "первый раз, звук [ай]", tip: "Мороженое в первый раз, ice начинается с гласного звука, значит an ice cream.", image: "park-ice-cream" },
        { text: "Vincent wants ___ ice cream too!", ru: "Винни тоже хочет это мороженое!", answer: "the", hint: "то самое", tip: "Винни хочет именно Варино мороженое, то самое, значит the ice cream.", image: "park-ice-cream" },
        { text: "There is ___ pond in the park.", ru: "В парке есть пруд.", answer: "a", hint: "первый раз, звук [п]", tip: "Пруд в первый раз, pond начинается с согласного, значит a pond.", image: "park-pond-ducks" },
        { text: "___ ducks on the pond are hungry.", ru: "Утки на пруду голодные.", answer: "the", hint: "те самые", tip: "Утки на этом пруду, те самые. The подходит и ко многим, значит the ducks.", image: "park-pond-ducks" },
        { text: "Look! ___ moon is in the sky.", ru: "Смотри! На небе луна.", answer: "the", hint: "единственная", tip: "Луна одна на свете, значит the moon.", image: "sky-moon" },
        { text: "Vincent has ___ umbrella. It is blue.", ru: "У Винни есть зонт. Он синий.", answer: "an", hint: "первый раз, звук [а]", tip: "Зонт в первый раз, umbrella начинается с гласного звука, значит an umbrella.", image: "park-umbrella" },
      ],
    },
    {
      id: "sort-articles",
      kind: "sort",
      kicker: "🧺 Сортировка",
      title: "В какой домик отправить слово?",
      trail: "Практика",
      bubble: {
        en: "Sort the words. Which little word goes with each one: a, an, the, or nothing?",
        ru: "Рассортируй слова. Какое маленькое слово нужно каждому: a, an, the или никакого?",
      },
      track: "l3-s4",
      points: 10,
      zones: [
        { id: "a", title: "a", sub: "первый раз, согласный" },
        { id: "an", title: "an", sub: "первый раз, гласный" },
        { id: "the", title: "the", sub: "тот самый, единственный" },
        { id: "none", title: "без слова", sub: "много предметов" },
      ],
      cards: [
        { label: "egg", sub: "яйцо, в первый раз", zone: "an" },
        { label: "bench", sub: "скамейка, в первый раз", zone: "a" },
        { label: "sun", sub: "солнце", zone: "the" },
        { label: "flowers", sub: "цветы, много", zone: "none" },
        { label: "orange", sub: "апельсин, в первый раз", zone: "an" },
        { label: "kite", sub: "змей, в первый раз", zone: "a" },
        { label: "moon", sub: "луна", zone: "the" },
        { label: "ducks", sub: "утки, много", zone: "none" },
      ],
      wrongTip: "Подумай: первый раз или тот самый? Один предмет или много? Гласный звук в начале?",
    },
    {
      id: "final",
      kind: "story",
      kicker: "🏁 Финальное испытание",
      title: "Рассказ о парке",
      trail: "Финал",
      bubble: {
        en: "Final round! Read the story and fill in the gaps. Fifteen points for each one. Let's go!",
        ru: "Финал! Прочитай рассказ и заполни пропуски. Пятнадцать баллов за каждый. Вперёд!",
      },
      track: "l3-s5",
      wrongBubble: "Почти! Первый раз или тот самый? Один или много? Гласный звук?",
      points: 15,
      text: "Last Sunday, Varya and Vincent were in {{1}} park near their school. There was {{2}} big tree and there were {{3}} flowers. {{4}} tree was near the playground. Varya had {{5}} apple and Vincent had {{6}} ball. {{7}} ball was yellow. {{8}} sun was hot, so they sat under the tree.",
      ru: "В прошлое воскресенье Варя и Винни были в парке рядом со школой. Там было большое дерево и цветы. Дерево стояло рядом с площадкой. У Вари было яблоко, а у Винни мяч. Мяч был жёлтый. Солнце припекало, поэтому они сели под дерево.",
      image: "park-friends",
      readTrack: "l3-story",
      options: ["a", "an", "the", "—"],
      gaps: [
        { answer: "the", tip: "Парк рядом со школой, мы знаем, какой именно. Тот самый, значит the park." },
        { answer: "a", tip: "Дерево называем в первый раз, big начинается с согласного, значит a big tree." },
        { answer: "—", tip: "Flowers, много цветов. С многими предметами a и an не ставим." },
        { answer: "the", tip: "Про дерево уже сказали, значит the tree." },
        { answer: "an", tip: "Яблоко в первый раз, apple начинается с гласного звука, значит an apple." },
        { answer: "a", tip: "Мяч в первый раз, ball начинается с согласного, значит a ball." },
        { answer: "the", tip: "Про мяч уже сказали, значит the ball." },
        { answer: "the", tip: "Солнце одно на свете, значит the sun." },
      ],
    },
  ],

  complete: {
    bubble: {
      en: "Brilliant! A, an and the are your friends now. High paw!",
      ru: "Блестяще, {name}! Теперь a, an и the твои друзья. Дай лапу!",
    },
    track: "l3-done",
    heading: "Артикли покорены!",
    lead: "Запомни главное. В первый раз: <b>a</b> или <b>an</b> (an перед гласным звуком). Тот самый или единственный: <b>the</b>. Много предметов: без a и an.",
    chips: ["🐕 a dog", "🍎 an apple", "☀️ the sun"],
  },
};
