// Урок 4. Was / were, there was / there were, could.
// Повторяет школьный текст «A day at the park» (Go Getter 2, Unit 5).

export default {
  id: "past",
  number: 4,
  title: "Вчера в парке",
  grammar: "was / were, there was / there were, could",
  emoji: "📸",
  cover: "cover-lesson-4",
  minutes: 15,
  badge: { name: "Time Traveller", emoji: "🕰️" },

  intro: {
    bubble: {
      en: "Hello, my friend! Last Sunday we were in the park. Let's remember what there was and what we could do!",
      ru: "Привет, {name}! В прошлое воскресенье мы были в парке. Давай вспомним, что там было и что мы могли делать!",
    },
    track: "l4-intro",
    heading: "Вчера в парке: was, were и could",
    lead: "Научись рассказывать о том, что <b>было</b>: was и were. И о том, что ты <b>мог</b> делать: could. Это ровно то, что нужно для рассказа «A day at the park».",
  },

  rule: {
    bubble: {
      en: "Was is for one: I was, he was. Were is for many: we were, they were. Could never changes!",
      ru: "Was для одного: I was, he was. Were для многих: we were, they were. А could никогда не меняется!",
    },
    track: "l4-rule",
    kicker: "🔎 Винни объясняет",
    heading: "Был, были, мог: was, were, could",
    note: "Was и were значат «был, была, было, были». Это то же самое is и are, только вчера. Правило старое: один, значит <b>was</b>. Много, значит <b>were</b>. Вопрос строится так же, как с is и are: слова меняются местами. Was it fun? Were you in the park? Could you ride a bike? Ответы: Yes, it was. No, we weren't. Yes, I could.",
    cards: [
      {
        title: "🐩 was",
        tone: "simple",
        html: "Один. I was, he was, she was, it was, Vincent was. Yesterday I was in the park. Вчера я был в парке. There <b>was</b> a big tree. Там было большое дерево. Если не был: <b>wasn't</b>.",
        formula: "I / he / she / it + <b>was</b><small>there was a tree</small>",
        examples: [{ en: "Last Sunday, I was in the park with my friends.", ru: "В прошлое воскресенье я был в парке с друзьями.", track: "l4-ex-1" }],
      },
      {
        title: "👧👧 were",
        tone: "now",
        html: "Много. We were, you were, they were, my friends were. We were happy. Мы были рады. There <b>were</b> many flowers. Там было много цветов. Слово you всегда с were, даже если ты один. Если не были: <b>weren't</b>.",
        formula: "we / you / they + <b>were</b><small>there were many flowers</small>",
        examples: [{ en: "There were many flowers in the park.", ru: "В парке было много цветов.", track: "l4-ex-2" }],
      },
      {
        title: "⚽ could",
        tone: "neutral",
        html: "«Мог, могла, могли, умел». Это can, только вчера. Could не меняется никогда: I could, she could, they could. The children could play football. Дети могли играть в футбол. Если не мог: <b>couldn't</b>.",
        formula: "I / she / they + <b>could</b> + play<small>could не меняется</small>",
        examples: [{ en: "The children could play football and ride bikes.", ru: "Дети могли играть в футбол и кататься на велосипедах.", track: "l4-ex-3" }],
      },
    ],
    button: "Вспомнить парк!",
  },

  stages: [
    {
      id: "was-were",
      kind: "sort",
      kicker: "🧺 Разминка",
      title: "Was или were?",
      trail: "Разминка",
      bubble: {
        en: "Sort the cards. One goes to 'was', many go to 'were'.",
        ru: "Рассортируй карточки. Один отправляй в домик was, много в домик were.",
      },
      track: "l4-s1",
      points: 10,
      zones: [
        { id: "was", title: "🐩 was", sub: "один: I, he, she, it" },
        { id: "were", title: "👧👧 were", sub: "много: we, you, they" },
      ],
      cards: [
        { label: "I", sub: "я", zone: "was" },
        { label: "we", sub: "мы", zone: "were" },
        { label: "Vincent", sub: "Винни", zone: "was" },
        { label: "my friends", sub: "мои друзья", zone: "were" },
        { label: "she", sub: "она", zone: "was" },
        { label: "they", sub: "они", zone: "were" },
        { label: "the tree", sub: "дерево", zone: "was" },
        { label: "the children", sub: "дети", zone: "were" },
      ],
      wrongTip: "Посчитай: это один или много? Один, значит was. Много, значит were.",
    },
    {
      id: "there-was",
      kind: "choice",
      kicker: "🎯 Что было в парке?",
      title: "There was или there were?",
      trail: "Практика",
      bubble: {
        en: "What was there in the park last Sunday? Choose was or were.",
        ru: "Что было в парке в прошлое воскресенье? Выбери was или were.",
      },
      track: "l4-s2",
      wrongBubble: "Почти! Посмотри на слово после there was. Один предмет или много?",
      points: 10,
      items: [
        { text: "There ___ a big tree in the park.", ru: "В парке было большое дерево.", options: ["was", "were"], answer: "was", tip: "A big tree, одно дерево. Один, значит was.", image: "park-tree", track: "l4-c-1" },
        { text: "There ___ many flowers under the tree.", ru: "Под деревом было много цветов.", options: ["was", "were"], answer: "were", tip: "Many flowers, много цветов. Много, значит were.", image: "park-flowers", track: "l4-c-2" },
        { text: "There ___ some children on the playground.", ru: "На площадке было несколько детей.", options: ["was", "were"], answer: "were", tip: "Some children, несколько детей. Много, значит were.", image: "park-playground", track: "l4-c-3" },
        { text: "There ___ a pond with ducks.", ru: "Там был пруд с утками.", options: ["was", "were"], answer: "was", tip: "A pond, один пруд. Один, значит was.", image: "park-pond-ducks", track: "l4-c-4" },
        { text: "There ___ two bikes near the bench.", ru: "Рядом со скамейкой было два велосипеда.", options: ["was", "were"], answer: "were", tip: "Two bikes, два велосипеда. Много, значит were.", image: "park-bikes", track: "l4-c-5" },
        { text: "There ___ a kite in the sky.", ru: "В небе был воздушный змей.", options: ["was", "were"], answer: "was", tip: "A kite, один змей. Один, значит was.", image: "park-kite", track: "l4-c-6" },
        { text: "There ___ three ducks on the pond.", ru: "На пруду было три утки.", options: ["was", "were"], answer: "were", tip: "Three ducks, три утки. Много, значит were.", image: "park-pond-ducks", track: "l4-c-7" },
        { text: "There ___ an ice cream for Vincent!", ru: "Для Винни было мороженое!", options: ["was", "were"], answer: "was", tip: "An ice cream, одно мороженое. Один, значит was.", image: "park-ice-cream", track: "l4-c-8" },
      ],
    },
    {
      id: "type-past",
      kind: "type",
      kicker: "✏️ Впиши сам",
      title: "Напиши was, were или could",
      trail: "Практика",
      bubble: {
        en: "Type was, were or could. Read the sentence carefully!",
        ru: "Напиши was, were или could. Внимательно читай предложение!",
      },
      track: "l4-s3",
      wrongBubble: "Почти! «Был» или «мог»? Один или много?",
      points: 15,
      placeholder: "was / were / could",
      items: [
        { text: "Last Sunday, I ___ in the park with my friends.", ru: "В прошлое воскресенье я был в парке с друзьями.", answer: "was", hint: "I: один, «был»", tip: "I, это один. «Был», значит was.", image: "park-friends" },
        { text: "My friends ___ there too.", ru: "Мои друзья тоже там были.", answer: "were", hint: "my friends: много", tip: "My friends, много. «Были», значит were.", image: "park-friends" },
        { text: "The children ___ play football.", ru: "Дети могли играть в футбол.", answer: "could", hint: "«могли»", tip: "«Могли», значит could. Could не меняется.", image: "park-football" },
        { text: "Vincent ___ run very fast.", ru: "Винни мог бегать очень быстро.", answer: "could", hint: "«мог»", tip: "«Мог», значит could.", image: "vincent-ball" },
        { text: "It ___ a sunny day.", ru: "Был солнечный день.", answer: "was", hint: "it: один, «был»", tip: "It, это один. «Был», значит was.", image: "sky-sun" },
        { text: "We ___ happy because we could play.", ru: "Мы были рады, потому что могли играть.", answer: "were", hint: "we: много", tip: "We, много. «Были», значит were.", image: "park-friends" },
        { text: "The big tree ___ near the playground.", ru: "Большое дерево было рядом с площадкой.", answer: "was", hint: "the tree: одно", tip: "The tree, одно дерево. «Было», значит was.", image: "park-tree" },
        { text: "Vincent ___ ride a bike. He is a dog!", ru: "Винни не мог кататься на велосипеде. Он же собака!", answer: "couldn't", alt: ["could not"], hint: "«не мог»", tip: "«Не мог», значит couldn't.", image: "park-bikes" },
      ],
    },
    {
      id: "build",
      kind: "build",
      kicker: "🧩 Конструктор",
      title: "Собери предложение",
      trail: "Практика",
      bubble: {
        en: "Put the words in the right order. Tap a word to add it, tap again to take it back.",
        ru: "Расставь слова по порядку. Нажми на слово, чтобы добавить его, и ещё раз, чтобы вернуть.",
      },
      track: "l4-s4",
      wrongBubble: "Почти! Сначала кто, потом was или were, потом где или что.",
      points: 15,
      items: [
        { answer: "Last Sunday I was in the park.", ru: "В прошлое воскресенье я был в парке.", extra: ["were"], image: "park-varya-vincent", track: "l4-b-1" },
        { answer: "There were many flowers.", ru: "Там было много цветов.", extra: ["was"], image: "park-flowers", track: "l4-b-2" },
        { answer: "The children could play football.", ru: "Дети могли играть в футбол.", extra: ["can"], image: "park-football", track: "l4-b-3" },
        { answer: "We were happy.", ru: "Мы были рады.", extra: ["was"], image: "park-friends", track: "l4-b-4" },
        { answer: "Was the tree near the playground?", ru: "Дерево было рядом с площадкой?", extra: ["were"], image: "park-tree", track: "l4-b-5" },
        { answer: "Vincent couldn't ride a bike.", ru: "Винни не мог кататься на велосипеде.", extra: ["could"], image: "park-bikes", track: "l4-b-6" },
      ],
    },
    {
      id: "final",
      kind: "story",
      kicker: "🏁 Финальное испытание",
      title: "Вопросы о прогулке",
      trail: "Финал",
      bubble: {
        en: "Final round! Answer the questions about our day in the park. Fifteen points for each one!",
        ru: "Финал! Ответь на вопросы о нашем дне в парке. Пятнадцать баллов за каждый!",
      },
      track: "l4-s5",
      wrongBubble: "Почти! Кто это: один или много? «Был» или «мог»?",
      points: 15,
      text: "Who {{1}} in the park? My friends {{2}} there. Where {{3}} the big tree? It {{4}} near the playground. What {{5}} the children do? They {{6}} play football.",
      ru: "Кто был в парке? Мои друзья были там. Где было большое дерево? Оно было рядом с площадкой. Что могли делать дети? Они могли играть в футбол.",
      image: "park-friends",
      readTrack: "l4-story",
      options: ["was", "were", "could"],
      gaps: [
        { answer: "was", tip: "Who, «кто», спрашиваем как про одного. «Был», значит was." },
        { answer: "were", tip: "My friends, много. «Были», значит were." },
        { answer: "was", tip: "The big tree, одно дерево. «Было», значит was." },
        { answer: "was", tip: "It, одно. «Было», значит was." },
        { answer: "could", tip: "«Что могли делать», значит could." },
        { answer: "could", tip: "«Могли играть», значит could play." },
      ],
    },
  ],

  complete: {
    bubble: {
      en: "Wonderful! Now you can tell everyone about our day in the park. High paw!",
      ru: "Чудесно, {name}! Теперь ты можешь рассказать всем о нашем дне в парке. Дай лапу!",
    },
    track: "l4-done",
    heading: "Прогулка вспомнилась!",
    lead: "Запомни главное. Один: <b>was</b>. Много: <b>were</b>. «Мог»: <b>could</b>, и оно не меняется.",
    chips: ["🐩 was", "👧👧 were", "⚽ could"],
  },
};
